spring:
  application:
    name: crawler-wa-tester
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/com_lmg_linkvalidator}
  jpa:
    hibernate:
      ddl-auto: update
env:
  prod:
    browserHeadless: true
    browserType: CHROME
    consumerThread: 2
    pollerRate: 2000
