spring:
  application:
    name: crawler-wa-tester
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/com_lmg_linkvalidator}
  jpa:
    hibernate:
      ddl-auto: create-drop
env:
  app:
    consumerThread: 2
    pollerRate: 2000
  prod:
    browserHeadless: true
  preprod:
    browserHeadless: true

# https://www.centrepointstores.com/kw/en
# https://blc.centrepointstores.com/kw/en

# curl -X POST http://localhost:8080/projects -H "Content-Type: application/json"  -d '{ "prodBaseUrl": "https://www.centrepointstores.com/kw/en", "preProdBaseUrl": "https://blc.centrepointstores.com/kw/en" }' | jq
# curl -X PUT http://localhost:8080/projects/start/1 | jq