spring:
  application:
    name: crawler-wa-tester
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
env:
  app:
    consumerThread: 2
    pollerRate: 2000
  prod:
    browserHeadless: true
    browserType: CHROME
