spring:
  application:
    name: crawler-wa-tester
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/com_lmg_linkvalidator}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties.hibernate.format_sql: true
    defer-datasource-initialization: true
  sql.init.mode: always
env:
  app:
    maxDepth: 5
    consumerThread: 6
    pollerRate: 1000
    pageWait: 5000
    browserHeadless: true
  process:
    pollerRate: 20000

# https://www.centrepointstores.com/kw/en
# https://blc.centrepointstores.com/kw/en

###
# curl -X POST http://localhost:8080/process -H "Content-Type: application/json" -d '{ "compareFrom": "https://www.centrepointstores.com/kw/en", "compareTo": "https://blc.centrepointstores.com/kw/en" }' | jq
# curl -X POST http://localhost:8080/reports/1 > data.csv
###
