spring:
  application:
    name: crawler-wa-tester
  datasource:
    driverClassName: org.postgresql.Driver
    username: {$DB_USERNAME}
    password: {$DB_PASSWORD}
    url: {$DB_URL}
env:
  prod:
    browserHeadless: true
    browserType: CHROME
    consumerThread: 2
    pollerRate: 1000
